### ISSUE TITLE
X1-AV-58 Velocity Calculations 

### ISSUE THREAD

**Issue by krislemie** [UVicRocketry/Xenia1-Flight-Computer#100]
# Description
 <Describe what the feature or bug that need to be resolved>
 <Description of the big component that encompasses the issue working on>
 <Depencies, ex. libraries, sensors, hardware, small parts of code youhave to work on>
 <ow to do the things>
 NOTE: if you import anything new add it to the list in `requirements.txt`

Take the calculated values from #76 and calculate velocities.

Create more functions in `datahandler.py` to calculate multiple velocity using different equations.

# Acceptance Criteria
 <Write specifically what is need for this issue to be completed>

- [ ] Create a list of equations to be used
- [ ] Create corresponding functions to equations
- [ ] Update class documentation explaining what params are need and what equation was used for each function
- [ ] Velocity is calculated 

# Dev Notes
[for assignee]<write down your thought process when developing this issue>

# Linked issues
 <If there are any related issues>
blocked by #76 
<Add to milestone>
