### ISSUE TITLE
Integrate Suborbit with FC

### ISSUE THREAD

**Issue by PokeyOne** [UVicRocketry/Xenia1-Flight-Computer#113]
# Description

[Suborbit](https://github.com/UVicRocketry/Suborbit-Prediction-Script) needs to be integrated with the flight computer.

# Acceptance Criteria

- [ ] `suborbit.py` should be an importable module.
- [ ] Should be some class that is initialized in the initialization step which loads all the data and setup needed.
- [ ] Should have methods for: predict height from height and vel, how much to adjust the airbrakes

# Linked Issues

There is definitely a linked issue.
