### ISSUE TITLE
X1-AV-17 Write Issues for air brakes plan 

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-flight-Computer#29]
**Description**
Read old repo (python airbrakes), if you are confused on anything talk to conner ebert our team lead. 
**Acceptance Criteria**
- Write new issues to break everything up project up into tasks
- Talk to @TechGal and @Kris to make sure they make sense to them

**Dev Notes**
[for assignee in PR]<write down your thought process when developing this issue>

**Linked issues**

**Comment by klemie** [comment]
Set a date for the meeting

**Comment by klemie** [comment]
Add issues to https://github.com/UVicRocketry/Xenia1-flight-Computer/milestone/3

**Comment by PokeyOne** [comment]
# Mateo's Dev Notes

This comment is a work in progress; I'm just writing some notes in a github comment as I work.

Here is a diagram from the "MECH400_FinalReport_Group13.pdf" docment available on GitHub
<img width="491" alt="Screen Shot 2022-03-16 at 15 23 34" src="https://user-images.githubusercontent.com/7290599/158701319-7747ac67-6f78-4999-a733-9dee6dc13ef4.png">

And here is another diagram from the "software in-the-loop testing" section of the same document. Figure 28: "Simulink Model of AACS Control System and Flight Dynamics"
<img width="617" alt="Screen Shot 2022-03-16 at 15 25 21" src="https://user-images.githubusercontent.com/7290599/158701528-46954840-e502-416d-8934-7936cf398d58.png">

*I'm just going to edit this comment as I work through components that this can be broken down into*. After discussing tonight, issues can be created and branches, and then get programming.

## Components/Tasks
Here's a sorta workflow type thing on what needs to be developed
```mermaid
flowchart LR
    Issues[Create Issues] --> sensor[Sensor Data Retrieval in One Object/Struct]
    Issues --> Kalman
    Kalman --> Drag[Drag Optimizer]
    Issues --> Output[What does output look like]
    sensor --> Kalman
    Drag --> Motor
    Kalman -- error data --> Motor[Motor Controller Convert Error into steps]
    Motor --> Output
    sensor --> State["Determine when system is active [1]"]
    State --> Motor
```
[1] See "5.2.6 Active Control Flight Envelope" section of the report.

In the first diagram of this comment, they mention the "State Observer" is where the Kalman stuff would be happening.

**Here are how I'm thinking of breaking this up**:
- [ ] Transform sensor input from raw data to interpretable numbers
- [ ] Make kalman take the input data and output error data.
- [ ] Drag Optimizer (Not sure what this will involve)
- [ ] Convert drag-op and kaman values into flap angles and motor steps
- [ ] Output data back to motor and self.
- [ ] control when system active/not

All stages should include testing of that stage.

## What I'm not Sure on
- Not sure the scope of the "air brakes" plan. Seems like this is less air brakes, and more just flight controller.
- What the drag optimizer 100% does.
- How much of that report we are following exactly and how much is changed in recent development.
- The flight dynamics section of the first graph.
- How are we testing stuff.

**Comment by klemie** [comment]
Discuss at meeting

**Comment by PokeyOne** [comment]
## Summary of results from meeting on this issue

There is a more detailed summary of the Airbrakes meeting on the Discord under AEROSTRUCTURE in the `# | airbrakes |` channel.

I will be translating a Matlab script we have into python and we will see how well it can predict final altitude of the rocket at different points in flight. If that script works, we may just use that script instead of a full Kalman filter to determine how much we need to deploy airbrakes.

**Comment by TechGal** [comment]
other predictive options: TinyML
