### ISSUE TITLE
X1-AV-23 Build simulation flight data set 

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#36]
# Description
 <Describe what the feature or bug that need to be resolved>
Look at old flight data and create a set of data to be used in testing the system 

# Acceptance Criteria

- [ ]  Simulation set should have all sensors, and a time stamp. Follow the same structure shown in Rocketdata.py
- [ ]  simulation set follows the same models an actaul flight 
- [ ]  Ask @MorganStuyt  for more info
# Dev Notes
[for assignee]<write down your thought process when developing this issue>

**Linked issues**
Blocks #35

**Comment by TechGal** [comment]
data may be weird. Temp readings weird
