### ISSUE TITLE
X1-AV-28 Threading

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#45]
# Description
Have individual threads for Air brakes, data handling. This will decouple the processes from one another and allow air brakes to work paralleled with sending and receiving data.

_Possible problems:_

1. Sending thread could be sending repeat if receiving thread isn't fast enough
[Possible solution]
- Keep sending and receiving data in one thread. Start by receiving then send once all data is collected (I suggest this one)
- Buffer sending thread to only send until receiving thread has collected all the data.
2. air brakes doesn't get updated sensor values in time. Could put the brakes in the wrong position. 

Note: use **https://docs.python.org/3/library/threading.html**

1. Initialize threads in `initialize()` phase. 
- use `_thread.start_new_thread()`, Takes a function as parameter function this will be the code that the thread executes.  
**create 2 threads:**
- one thread for moving air brakes 
- one thread for everything else
2. In the `coast_flight` calculate initial suborbit guess
3. In the `coast_flight` phase send airbrakes thread(AB) percentage value and move the motor
- AB thread will move the motor then send a finished flag to the main thread
- Once the main thread receives finished flag it will suborbit again and send that  
4. 

# Acceptance Criteria
- [ ] Threads handle main processes, Air brakes
- [ ] Checks are made to make sure all data has been received 
- [ ] Make sure air brakes thread receives data from data handling thread 

**Dev Notes**
[for assignee in PR]<write down your thought process when developing this issue>

**Linked issues**
#22

**Comment by klemie** [comment]
Monday: 6pm, threading meeting

**Comment by TechGal** [comment]
Moter needs to know length of time on sleep, to determine when and if it should move. Wont need threading, rework airbrakes slighty to get rid of sleep
