### ISSUE TITLE
X1-AV-40 Calc altitude 

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#76]
**Description**
There are about 3 different ways we can calculate altitude with the sensor data we have. We want to calculate current altitude in those three different ways compare them against eachother and send the result to airbrakes. 

create a file called calculations.py and put these 3 calculation in there.
**Acceptance Criteria**

- [ ] multiple calculations of altitude are made 
- [ ] a method to compare the calculated values is decided. 
- [ ] Error handling checking if compare values are to different 

**Dev Notes**
[for assignee]<write down your thought process when developing this issue>

**Linked issues**
 <If there are any related issues>

<Add to milestone>

**Comment by jjderooy** [comment]
What sensors are available for calculating altitude?
