### ISSUE TITLE
X1-AV-41 format rocketdata to transmitter state

### ISSUE THREAD

**Issue by krislemie** [UVicRocketry/Xenia1-Flight-Computer#78]
# Description
Work with @TechGal to hack the message for the transmitter. Once figured out how to access the message take the formatted data from RocketData.convert_to_csv_string and format the data to a string and set the message value in the transmitter.
 
# Acceptance Criteria
 <Write specifically what is need for this issue to be completed>

- [ ] Figure out how to Hack the message field of the transmitter
- [ ] Create a case in csv string function in rocketdata to create a string with only the most import sensor data Char limit of 200c. Do 4 sig figs
- [ ] Write a function to update text field (writtin in send data)
- [ ] Test with actual transmitter to make sure field sends 

# Dev Notes
[for assignee]<write down your thought process when developing this issue>

# Linked issues
 <If there are any related issues>
Similar to #37 
<Add to milestone>

**Comment by jjderooy** [comment]
Can you give some more context of how the transmitter connects? Name of transmitter, and libraries it uses that sort of thing? @TechGal any parameters we need to know about the antenna like character limits, packet frequency etc?

**Comment by krislemie** [comment]
char limit is 200 but thats all I know

**Comment by TechGal** [comment]
We're using the BigRedBee 70cm APRS [transmitter](https://shop.bigredbee.com/products/70cm-100mw-gps-aprs-transmitter). This transmitter uses a microcontroller which is initially programmed on a Windows computer, including a message which is sent to the ground with the automated GPS data and timestamp. The thing that needs to be determine is whether or not we can use the exposed UART interface to send a new message once / second (the recommended transmission speed). There are some programmers available, and I imagine there are some libraries too, for this microcontroller, but as this specific board is only used in a specific niche, I haven't found any tutorials explicitly discussing this board.

**Comment by krislemie** [comment]
150c aprs package. Choose key values from rocketData to send.

**Comment by krislemie** [comment]
we should figure out together in CDR
