### ISSUE TITLE
X1-AV-43 Update rocketData with sensor values

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#81]
# Description
Currently code has been written to read the sensor data from the IMU and LSM  into print statements. We need to change that to updating a rocketdata instance in main.

1. to do this we will update `__readBME280` and `__readLSM9DS1` by changing the print statements to a single return statement of an object that resembles what the print statements looked like. 
eg:
```
print("Temperature: %0.1f C" % self.__bme280.temperature)
print("Humidity: %0.1f %%" % self.__bme280.humidity)
print("Pressure: %0.1f hPa" % self.__bme280.pressure)
``` 
->
```
return {
     't': self.__bme280.temperature
     ....
}
```
make sure to write fullnames for object keys

2. Create a public varaible of type RocketData (import rocketdata add initialize a new instance)

3. A public function will have to be made to return all updated sensor values. This function will call `__readBme` and `__readLsm` update the public rocketdata variable with the Bme and lsm values

---

These imports were accidentally deleted please add back to the top of gpioReader. 
```
import board
import adafruit_lsm9ds1
from adafruit_bme280 import basic as adafruit_bme280
``` 
Also add imports to requirements.txt (board, adafruit_lsm9ds1, adafruit_bme280 )

---

test your code by running the code with the Mocks and printing out the state of call the public function (should return a rocketdata object). Maybe try running print statement in a for loop in main. Merged version of code will not include this testing code.

# Acceptance Criteria

- [ ]   imports are added in requirement.txt and to the top of gpioReader
- [ ] Screenshot of test results in PR
- [ ] __readBME & __readLSM are change to return objects
- [ ] A public function is created that update a public attribute of type rocketData with the values from `__readBME` & `readLSm`
# Dev Notes
[for assignee]<write down your thought process when developing this issue>

**Linked issues**
 <If there are any related issues>

<Add to milestone>
