### ISSUE TITLE
X1-AV-50 Redo Sensor power Calculation 

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#83]
# Description
 <Describe what the feature or bug that need to be resolved>
 <Description of the big component that encompasses the issue working on>
 <Depencies, ex. libraries, sensors, hardware, small parts of code youhave to work on>
 <ow to do the things>

Calculations with for sensors are done correctly and checked by other members

# Acceptance Criteria
 <Write specifically what is need for this issue to be completed>

- [x] Power Calculation include all up to date sensor
- [x] Confirm if we have enough power to last +6hr
- [x] Update documentation
- [x] Choose lipos or 9V

# Dev Notes
[for assignee]<write down your thought process when developing this issue>

# Linked issues
 <If there are any related issues>

<Add to milestone>
