### ISSUE TITLE
X1-AV-51 Choose GoNoGo indicator 

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#84]
# Description
 <Describe what the feature or bug that need to be resolved>
 <Description of the big component that encompasses the issue working on>
 <Depencies, ex. libraries, sensors, hardware, small parts of code youhave to work on>
 <ow to do the things>
 NOTE: if you import anything new add it to the list in `requirements.txt`

Choose a sensor indicator and have a diagram for start up sequence that will trigger the indicator

# Acceptance Criteria
 <Write specifically what is need for this issue to be completed>

- [ ] Choose an indicator. LED vs. Buzzer?
- [ ] Update CAD with indicator 
- [ ] Create a flow diagram for the startup sequence 
- [ ] Write follow up ticket for software implementation

# Dev Notes
[for assignee]<write down your thought process when developing this issue>

# Linked issues
 <If there are any related issues>

<Add to milestone>
