### ISSUE TITLE
X1-AV-53 Change stepper driver for airbrakes 

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#85]
# Description

Spec new more reliable stepper driver for airbrakes. @Devon-H knows the right one

# Acceptance Criteria

- [x] Integrate new sensor in cad 
- [ ] Learn how to control it with python
- [ ] Implement into `src/airbrakes.py`
- [ ] Test that it works

# Dev Notes

# Linked issues

**Comment by Devon-H** [comment]
The stepper motor driver in question is the DRV8825. Here's an amazon [link](https://www.amazon.ca/Baluue-Stepper-Compatible-StepStick-Printer/dp/B08PV6JTK7/ref=sr_1_43?crid=9692R8CDHXYP&keywords=stepper+motor+driver&qid=1653415285&sprefix=stepper+motor+drive%2Caps%2C209&sr=8-43) for reference

**Comment by PokeyOne** [comment]
I just got assigned to this, but this may or may not already be finished. I know for a fact that I already updated the schematic, but I haven't looked at the code. I'll take a look later today.

If it is already updated, I will still want to test that it works before closing this issue.
