### ISSUE TITLE
X1-AV-54 Order Corssed-Yagi

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#86]
# Description
 <Describe what the feature or bug that need to be resolved>
 <Description of the big component that encompasses the issue working on>
 <Depencies, ex. libraries, sensors, hardware, small parts of code youhave to work on>
 <ow to do the things>

Order Crossed-Yagi

# Acceptance Criteria
 <Write specifically what is need for this issue to be completed>

 -  [x] Pick an antenna
 -  [x] Send to Levente for feedback
 -  [x] On receipt on feedback, add to procurement sheet

# Dev Notes
[for assignee]

THIS WAS NOT NECESSARY

While the issue was completed, it was pointed out that the antenna recommended by experts was excessive, and given that we were changing other portions of the telemetry system without testing, was not a prudent allocation of resources.

# Linked issues
 <If there are any related issues>

<Add to milestone>
