### ISSUE TITLE
X1-AV-56 standardize apogee prediction and startup

### ISSUE THREAD

**Issue by krislemie** [UVicRocketry/Xenia1-Flight-Computer#88]
# Description
 <Describe what the feature or bug that need to be resolved>
 <Description of the big component that encompasses the issue working on>
 <Depencies, ex. libraries, sensors, hardware, small parts of code you have to work on>
We have a couple different systems on the rocket that need to know apogee and starting launch. Based on the available sensors we need to create a universal way throughout the rocket to know when the launch has happened, and when the rocket has reached apogee.

# Acceptance Criteria
 <Write specifically what is need for this issue to be completed>

- [ ] Gather a list of sensor values available in all three systems (black berry jam, magpi, flight computer) you will have to talk to @cristyro & @Gordon-928 for details.
- [ ] Figure out what sensor values will dictate a launch
- [ ] Create function in `dataHadler.py` to return true when launch is detected
- [ ] Figure out what value will dictate of apogee 
- [ ] Create function in `dataHadler.py` to return true when apogee is detected
- [ ] Work with @cristyro & @Gordon-928 to make C++ versions

# Dev Notes
[for assignee]<write down your thought process when developing this issue>

# Linked issues
 <If there are any related issues>

<Add to milestone>
