### ISSUE TITLE
Test USB Type-C to ethernet from fridge (?) with Raspberry Pi

### ISSUE THREAD

**Issue by TechGal** [UVicRocketry/Xenia1-Flight-Computer#90]
# Description
 <Describe what the feature or bug that need to be resolved>
 <Description of the big component that encompasses the issue working on>
 <Depencies, ex. libraries, sensors, hardware, small parts of code youhave to work on>
 <ow to do the things>
 NOTE: if you import anything new add it to the list in `requirements.txt`

Choose a sensor indicator and have a diagram for start up sequence that will trigger the indicator

# Acceptance Criteria
 <Write specifically what is need for this issue to be completed>

- [ ] Retrieve connector from fridge in RR
- [ ] Plug in connector and RPi Zero W
- [ ] See if RPi Zero W can be accessed from laptop
- [ ] Relay instructions to Avionics on how to use

# Dev Notes
[for assignee]<write down your thought process when developing this issue>

# Linked issues
 <If there are any related issues>

<Add to milestone>
