### ISSUE TITLE
Spec ground station equipment

### ISSUE THREAD

**Issue by TechGal** [UVicRocketry/Xenia1-Flight-Computer#93]
# Description
 <Describe what the feature or bug that need to be resolved>
 <Description of the big component that encompasses the issue working on>
 <Depencies, ex. libraries, sensors, hardware, small parts of code youhave to work on>
 <ow to do the things>
 NOTE: if you import anything new add it to the list in `requirements.txt`

Choose a sensor indicator and have a diagram for start up sequence that will trigger the indicator

# Acceptance Criteria
 <Write specifically what is need for this issue to be completed>

- [x] Spec LNA, limiter, crossed-yagi antenna for groundstation
- [x] Send list to Levente for feedback 
- [x] On response, add to procurement sheet

# Dev Notes
[for assignee]<write down your thought process when developing this issue>

# Linked issues
 <If there are any related issues>

<Add to milestone>
