### ISSUE TITLE
How to use ground station as full duplex receiver

### ISSUE THREAD

**Issue by TechGal** [UVicRocketry/Xenia1-Flight-Computer#97]
# Description
 <Describe what the feature or bug that need to be resolved>
 <Description of the big component that encompasses the issue working on>
 <Depencies, ex. libraries, sensors, hardware, small parts of code youhave to work on>
 <ow to do the things>
 NOTE: if you import anything new add it to the list in `requirements.txt`

Choose a sensor indicator and have a diagram for start up sequence that will trigger the indicator

Note that each transmitter will be sending at 1Hz.

# Acceptance Criteria
 <Write specifically what is need for this issue to be completed>

- [ ] How to set up an RTL-SDR to receive two signals at once (full duplex), or monitor two frequencies at once (half duplex)
- [ ] Update software on ground station to include this 
- [ ] Test receiving two signals at once 

# Dev Notes
[for assignee]<write down your thought process when developing this issue>

# Linked issues
 <If there are any related issues>

<Add to milestone>
